<?php
include("connect.php");

// GET THE INST.
// GET THE OPENING DATE OF THE ACCOUNT
// IF THOSE ACCOUNT DOES NOT HAVE A TABLE PART FOR THE CHARGE HISTORY
// ALLOCATE THE CHARGE TO A GL RUNNING FOR SAVINGS ACCOUNT
?>